name: Build & Test (CI)

on: workflow_dispatch
#on: [push, pull_request]

jobs:
  build_and_test:
    name: Prepare and build on Windows Server 2016 VM
    runs-on: windows-2016
    timeout-minutes: 30
    #continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies into Virtual Environment...
      run: ./_RegisterHelixNUnit.bat

    - name: Build C# project in Debug-mode, compile Pas-units, run tests, create install packages...
      env: 
        PABCNET_BUILD_MODE: Debug
        PABCNET_RUN_TESTS: true
        PABCNET_INC_BUILD: false
        PABCNET_NOT_VERBOSE: false
      run: ./_GenerateAllSetups_CI.bat

    - name: Publish artifacts (1/4)...
      uses: actions/upload-artifact@v2.1.0
      with:
        name: PascalABCNET_Win7_IDE_Full
        path: Release/PascalABCNETSetup.exe
        
    - name: Publish artifacts (2/4)...
      uses: actions/upload-artifact@v2.1.0
      with:
        name: PascalABCNET_Win7_IDE_Mini
        path: Release/PascalABCNETMiniSetup.exe

    - name: Publish artifacts (3/4)...
      uses: actions/upload-artifact@v2.1.0
      with:
        name: PascalABCNET_WinXP_IDE_Full
        path: Release/PascalABCNETWithDotNet40Setup.exe
        
    - name: Publish artifacts (4/4)...
      uses: actions/upload-artifact@v2.1.0
      with:
        name: PascalABCNET_Win_Mac_Linux_console
        path: Release/PABCNETC.zip
        
    #- name: Publish artifacts (5/5)...
    #  uses: actions/upload-artifact@v2.1.0
    #  with:
    #    name: All_distros
    #    path: Release
